Add files via upload

diff --git a/cursely_modpack b/cursely_modpack
--- a/cursely_modpack
+++ b/cursely_modpack
@@ -17,4 +17,10 @@ echo
 echo "Connecting to GitHub..."
 
 wget --no-cache --no-cookies "https://raw.githubusercontent.com/Julynx/cursely/main/${modpack}.md" -O "${temp_dir}/${modpack}.md" > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+  echo
+  echo "Modpack '$1' not found."
+  echo
+  exit 1
+fi
 cursely "${temp_dir}/${modpack}.md"
